version: '3.3'
services:
  uno-frontend:
    ports:
      - '3000:3000'
    image: een/frontend
    build: ./frontend
    restart: unless-stopped
  uno-backend:
    ports:
      - '5000:80'
    image: een/backend
    build: ./backend
    restart: unless-stopped

