version: '3.3'
services:
  uno-frontend:
    ports:
      - '3000:3000'
    image: uno-frontend
    restart: unless-stopped
  uno-backend:
    ports:
      - '4000:5000'
    image: uno-backend
    restart: unless-stopped
